name: sample1

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sample1-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git status
      - run: git branch

